const EXERCISES = [
  { id: 'ex_01', name: 'Bodyweight Squat', level: 'beginner', tags: ['full_body', 'strength', 'compound'], muscles: ['Quads', 'Glutes', 'Core'], sets: 3, reps: 15, restSec: 60, caloriesPerSet: 8, image: '/exercises/squat.gif', instructions: ['Stand feet shoulder-width apart.', 'Lower hips back and down until thighs are parallel.', 'Drive through heels to stand.'], safetyTips: 'Keep knees tracking over toes; don\'t let them cave in.' },
  { id: 'ex_02', name: 'Push-Up', level: 'beginner', tags: ['strength', 'full_body', 'compound'], muscles: ['Chest', 'Shoulders', 'Triceps'], sets: 3, reps: 12, restSec: 60, caloriesPerSet: 7, image: '/exercises/pushup.gif', instructions: ['Hands under shoulders, body in a straight line.', 'Lower chest to floor.', 'Press back up.'], safetyTips: 'Keep core braced to avoid sagging hips.' },
  { id: 'ex_03', name: 'Walking Lunge', level: 'beginner', tags: ['strength', 'full_body'], muscles: ['Quads', 'Glutes', 'Hamstrings'], sets: 3, reps: 10, restSec: 45, caloriesPerSet: 8, image: '/exercises/lunge.gif', instructions: ['Step forward into a lunge.', 'Lower back knee toward floor.', 'Push off to bring feet together, alternate legs.'], safetyTips: 'Keep front knee behind toes.' },
  { id: 'ex_04', name: 'Plank', level: 'beginner', tags: ['mobility', 'low_impact', 'full_body'], muscles: ['Core'], sets: 3, durationSec: 30, restSec: 30, caloriesPerSet: 4, image: '/exercises/plank.gif', instructions: ['Forearms on floor, body straight line from head to heels.', 'Brace core and hold.'], safetyTips: 'Don\'t let hips sag or pike up.' },
  { id: 'ex_05', name: 'Jumping Jacks', level: 'beginner', tags: ['cardio', 'hiit', 'full_body'], muscles: ['Full Body'], sets: 3, durationSec: 45, restSec: 30, caloriesPerSet: 10, image: '/exercises/jumping-jacks.gif', instructions: ['Jump feet out while raising arms overhead.', 'Jump back to start.'], safetyTips: 'Land softly, knees slightly bent.' },
  { id: 'ex_06', name: 'Cat-Cow Stretch', level: 'beginner', tags: ['flexibility', 'mobility', 'low_impact'], muscles: ['Spine', 'Core'], sets: 2, reps: 10, restSec: 20, caloriesPerSet: 2, image: '/exercises/cat-cow.gif', instructions: ['On hands and knees, arch back looking up (cow).', 'Round spine tucking chin (cat).'], safetyTips: 'Move slowly with breath.' },
  { id: 'ex_07', name: 'Goblet Squat', level: 'intermediate', tags: ['strength', 'hypertrophy', 'compound'], muscles: ['Quads', 'Glutes', 'Core'], sets: 4, reps: 12, restSec: 75, caloriesPerSet: 9, image: '/exercises/goblet-squat.gif', instructions: ['Hold dumbbell/kettlebell at chest.', 'Squat down keeping chest tall.', 'Drive up through heels.'], safetyTips: 'Keep the weight close to your torso.' },
  { id: 'ex_08', name: 'Dumbbell Row', level: 'intermediate', tags: ['strength', 'hypertrophy'], muscles: ['Back', 'Biceps'], sets: 4, reps: 10, restSec: 75, caloriesPerSet: 8, image: '/exercises/db-row.gif', instructions: ['Hinge at hips, flat back.', 'Row dumbbell to hip.', 'Lower with control.'], safetyTips: 'Avoid rounding the lower back.' },
  { id: 'ex_09', name: 'Kettlebell Swing', level: 'intermediate', tags: ['cardio', 'hiit', 'strength', 'endurance'], muscles: ['Glutes', 'Hamstrings', 'Core'], sets: 4, reps: 15, restSec: 45, caloriesPerSet: 12, image: '/exercises/kb-swing.gif', instructions: ['Hinge and swing kettlebell between legs.', 'Drive hips forward to swing to chest height.'], safetyTips: 'Power comes from hips, not arms.' },
  { id: 'ex_10', name: 'Interval Running', level: 'intermediate', tags: ['cardio', 'endurance', 'hiit'], muscles: ['Legs', 'Cardiovascular'], sets: 6, durationSec: 60, restSec: 60, caloriesPerSet: 14, image: '/exercises/interval-run.gif', instructions: ['Sprint for 60s.', 'Walk/jog 60s to recover.', 'Repeat.'], safetyTips: 'Warm up 5 minutes before intervals.' },
  { id: 'ex_11', name: 'Romanian Deadlift', level: 'advanced', tags: ['strength', 'hypertrophy', 'compound'], muscles: ['Hamstrings', 'Glutes', 'Back'], sets: 4, reps: 8, restSec: 90, caloriesPerSet: 10, image: '/exercises/rdl.gif', instructions: ['Hinge at hips with slight knee bend, bar close to legs.', 'Lower until hamstring stretch, drive hips forward to stand.'], safetyTips: 'Keep spine neutral throughout.' },
  { id: 'ex_12', name: 'Pull-Up', level: 'advanced', tags: ['strength', 'hypertrophy', 'compound'], muscles: ['Back', 'Biceps'], sets: 4, reps: 8, restSec: 90, caloriesPerSet: 9, image: '/exercises/pullup.gif', instructions: ['Hang from bar, hands shoulder width.', 'Pull chin over bar.', 'Lower under control.'], safetyTips: 'Avoid kipping/swinging if training strict strength.' },
  { id: 'ex_13', name: 'Burpees', level: 'advanced', tags: ['cardio', 'hiit', 'full_body'], muscles: ['Full Body'], sets: 5, reps: 12, restSec: 45, caloriesPerSet: 15, image: '/exercises/burpee.gif', instructions: ['Squat, kick feet to plank, push-up.', 'Jump feet in, explode up with a jump.'], safetyTips: 'Scale by removing the push-up or jump if needed.' },
  { id: 'ex_14', name: 'Yoga Sun Salutation', level: 'beginner', tags: ['flexibility', 'mobility', 'low_impact'], muscles: ['Full Body'], sets: 2, reps: 5, restSec: 20, caloriesPerSet: 5, image: '/exercises/sun-salutation.gif', instructions: ['Flow through forward fold, plank, upward dog, downward dog.', 'Move with steady breath.'], safetyTips: 'Move within a pain-free range.' },
  { id: 'ex_15', name: 'Farmer\'s Carry', level: 'intermediate', tags: ['strength', 'full_body', 'endurance'], muscles: ['Grip', 'Core', 'Traps'], sets: 3, durationSec: 40, restSec: 60, caloriesPerSet: 9, image: '/exercises/farmers-carry.gif', instructions: ['Hold heavy dumbbells at sides.', 'Walk with tall posture and braced core.'], safetyTips: 'Keep shoulders back, avoid leaning.' }
];

module.exports = { EXERCISES };
